WIP: Correct login-redirect-to-unauthorized bug.
Cant-Stop-Columbus/vaccinateoh pull request #7
Opened 2021-03-20 20:28 UTC by hawkinsw

2021-03-20 20:58 UTC, BradGriffith requested changes

2021-03-20 20:58 UTC, BradGriffith commented on src/resources/js/Pages/Dashboard.vue
> +                        <h1><a href=/>Take me to the map!</a></h1>
I would avoid an H1 for this. Just using the link should be fine. With TailwindCSS, pretty much all styles are stripped, so using an h1 doesn't have any effect visually. And some quotes around the / would be good. :-)

2021-03-20 23:46 UTC, hawkinsw commented
Will do! Thanks for the quick reply and the great feedback!

On Sat, Mar 20, 2021 at 4:58 PM Brad Griffith ***@***.***>
wrote:

> *@BradGriffith* requested changes on this pull request.
> ------------------------------
>
> In src/resources/js/Pages/Dashboard.vue
> <https://github.com/Cant-Stop-Columbus/vaccinateoh/pull/7#discussion_r598159116>
> :
>
> > @@ -4,8 +4,13 @@
>          <div class="container mx-auto">
>              <!-- Page Heading -->
>              <header class="bg-white shadow">
> -                <div class="py-6 px-4 sm:px-6 lg:px-8">
> -                    <h1 class="text-2xl">VaccinateOH Stats</h1>
> +                <div class="flex items-center justify-between">
> +                    <div class="py-6 px-4 sm:px-6 lg:px-8">
> +                        <h1 class="text-2xl">VaccinateOH Stats</h1>
> +                    </div>
> +                    <div>
> +                        <h1><a href=/>Take me to the map!</a></h1>
>
> I would avoid an H1 for this. Just using the link should be fine. With
> TailwindCSS, pretty much all styles are stripped, so using an h1 doesn't
> have any effect visually. And some quotes around the / would be good. :-)
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Cant-Stop-Columbus/vaccinateoh/pull/7#pullrequestreview-616943798>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACCP2CTE55IAPABAIQDPOBDTEUEARANCNFSM4ZQY6VRQ>
> .
>

2021-03-21 14:20 UTC, BradGriffith approved these changes

2021-03-21 14:20 UTC, merged